name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build src/PortableDocument.sln
    - name: Unit Test
      shell: python3 {0}
      run: |
        import os
        import os.path
        import re
        import subprocess

        for file in os.listdir('src'):
            if re.match(r'^.+\.Tests$', file) is None:
                continue
            subprocess.run(['dotnet', 'test', os.path.join('src', file)], check=True)
