name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      shell: cmd
      run: msbuild.exe src\PortableDocument.sln
    - name: Unit Test
      shell: powershell
      run: |
        Get-ChildItem -Path src -Filter *.Tests -Directory | ForEach-Object {
          $name = $_.Name
          $path = $_.FullName

          $runner = Start-Process -FilePath vstest.console.exe -ArgumentList $path\bin\Debug\net48\$name.dll -Wait

          if ($runner.ExitCode -ne 0) {
            exit 1
          }
        }
