name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Setup .NET Core 2.2
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.207
    - name: Build
      shell: cmd
      run: dotnet.exe build src\PortableDocument.sln
    - name: Unit Test
      run: |
        Get-ChildItem -Path src -Filter *.Tests -Directory | ForEach-Object {
            $path = $_.FullName
            $runner = Start-Process -FilePath dotnet.exe -ArgumentList test, --no-build, -v=normal, $path -NoNewWindow -PassThru -Wait

            if ($runner.ExitCode -ne 0) {
                exit $runner.ExitCode
            }
        }
